version: '3.8'

services:
  app:
    image: hassan/backend:0.0.1
    ports:
      - 2020:2020
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sw2_project?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sw2_project
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"

